Introduce `pickTarget` and `pickPackage` command variables
bazelbuild/vscode-bazel pull request #354
Opened 2024-03-03 19:09 UTC by vogelsgesang

This commit introduces the `bazel.pickTarget` and `bazel.pickPackage` command variables. Those commands can be used from `tasks.json` and `launch.json` to prompt the user to select a Bazel target or package. The available choices are determined by a user-specified Bazel query.

The implementation reuses the existing quick-pick functionality from `bazel_quickpick.ts`. The `wrapQuickPick` function parses the arguments passed from the `task.json` and then forwards to the existing quickpicks.

Those utility functions were restructured as part of this commit:
1. The internal helpers `queryWorkspaceQuickPickPackages` and `queryWorkspaceQuickPickTargets` were inlined into `queryQuickPick{Packages,Targets}` as the internal helper functions got in the way of other changes, but didn't deduplicate any code as they only had one caller.
2. The `queryQuickPick{Packages,Targets}` take an object with named parameters now.
3. `queryQuickPickPackage` now also accepts a `query` parameter instead of using the `queryExpression`. Both `queryQuickPickPackages` and `queryQuickPickTargets` default to the query `//...` if no query string is provided by the caller.

Point (3) also is a user-facing change. Commands like "Build package" and "Test package" now use `//...` instead of the configured `queryExpression`. This is in sync with other commands like "Test target" which uses the hardcoded query `kind('.*_test rule', ...)`.

2024-03-17 16:39 UTC, vogelsgesang commented
@cameron-martin @jfirebaugh do you have time to review this? In case you currently don't have time to review in detail, I would appreciate high-level feedback whether you consider this functionality as valuable in general 🙂

2024-03-31 18:16 UTC, cameron-martin commented
I've been on holiday but I reckon I'll be able to take a look next week. The functionality does look useful though.

2024-04-01 14:56 UTC, vogelsgesang commented
By the way: I think long-term it would make sense to also add support for `cquery` and parameters such as [--experimental_explicit_aspects](https://bazel.build/reference/command-line-reference#flag--experimental_explicit_aspects), [--universe_scope](https://bazel.build/reference/command-line-reference#flag--universe_scope), [--infer_universe_scope](https://bazel.build/reference/command-line-reference#flag--infer_universe_scope), [--noimplicit_deps](https://bazel.build/reference/command-line-reference#flag--implicit_deps). But I will leave that for a different commit.

2024-04-02 12:56 UTC, cameron-martin requested changes
Apart from the two other comments, looks good.

2024-04-02 12:56 UTC, cameron-martin commented on README.md
I know this is existing, but this JSON should go in the `tasks.json` file, not `launch.json` as mentioned here.

2024-04-02 13:41 UTC, vogelsgesang commented on src/assert.ts
> +export function assert(value: boolean): asserts value {
good catch! Fixed

2024-04-02 13:42 UTC, vogelsgesang commented on README.md
I actually introduced this issue myself in a previous commit... more than happy to fix it :)

2024-04-02 13:46 UTC, cameron-martin approved these changes

2024-04-02 13:46 UTC, merged